#include <iostream>
#include <istream>
#include <sstream>
#include <cstdlib>
#include <cstdio>
#include <stack>
#include <map>
#include <vector>
#include <algorithm>
#include <string>
#include <cmath>
#include <bitset>
#include <memory>

using std::cin;
using std::cout;
using std::endl;
using std::string;
using std::to_string;
